name: get_instance
description: A smart dependency injector to GetXâ„¢ framework.
version: 3.10.2
homepage: https://github.com/jonataslaw/getx

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  get_core:
    path: ../get_core
  
dev_dependencies:
  test: ">=1.0.0 <2.0.0"
  test_coverage: ">=0.4.3 <1.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
