#The name of your workflow.
name:  Test, build and deploy
# Trigger the workflow on push or pull request
on: [push,pull_request]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:

  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: macos-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.1'
          channel: 'stable'
      - run: flutter pub get
      # run static analys code
      - run: flutter  analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
      # Upload coverage reports to Codecov
      # https://github.com/marketplace/actions/codecov
